version: '3.3'

services:
    react:
        container_name: mern_shop_react
        image: tobiwankenobii/mern_shop_react
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000

    express:
        container_name: mern_shop_express
        image: tobiwankenobii/mern_shop_express
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
